import {
  BOOKING_HEADERS,
  PAYMENT_HEADERS,
  buildBookingReportRows,
  buildPaymentReportRows,
} from "./aggregation";
import type { BookingSource, PaymentSource, SourceRecord } from "./aggregation";

function recordFrom(headers: readonly string[], values: SourceRecord): SourceRecord {
  return Object.fromEntries(headers.map((header) => [header, values[header] ?? ""]));
}

export const bookingSources: BookingSource[] = [
  {
    internalCompany: "Crown H&H",
    source: recordFrom(BOOKING_HEADERS, {
      Property: "Crown House",
      "Booking Date": "2026-10-01",
      "Booking Reference": "EV-28491",
      "Order Reference": "ORD-28491",
      "Guest First Name": "Amelia",
      "Guest Last Name": "Carter",
      "Check In": "2026-10-12",
      "Check Out": "2026-10-15",
      Nights: "3",
      "Room/Unit Type": "Deluxe",
      "Room/Unit Name": "Room 4",
      Currency: "GBP",
      "Total Revenue": "100.00",
      "Paid Amount": "100.00",
      "Room/Unit Revenue": "100.00",
      "Booking Status": "Confirmed",
      Channel: "Direct",
    }),
  },
  {
    internalCompany: "Crown Harbor",
    source: recordFrom(BOOKING_HEADERS, {
      Property: "Crown Harbor",
      "Booking Date": "2026-09-30",
      "Booking Reference": "EV-28490",
      "Order Reference": "ORD-28490",
      "Guest First Name": "Oliver",
      "Guest Last Name": "Bennett",
      "Check In": "2026-10-11",
      "Check Out": "2026-10-14",
      Nights: "3",
      "Room/Unit Type": "Family",
      "Room/Unit Name": "Suite 2",
      Currency: "GBP",
      "Total Revenue": "67.00",
      "Paid Amount": "67.00",
      "Room/Unit Revenue": "60.00",
      "Other Revenue": "7.00",
      "Booking Status": "Confirmed",
      Channel: "Direct",
    }),
  },
  {
    internalCompany: "Crown Orlando",
    source: recordFrom(BOOKING_HEADERS, {
      Property: "Crown Orlando",
      "Booking Date": "2026-09-29",
      "Booking Reference": "EV-28489",
      "Order Reference": "ORD-28489",
      "Guest First Name": "Sofia",
      "Guest Last Name": "Mitchell",
      "Check In": "2026-10-10",
      "Check Out": "2026-10-13",
      Nights: "3",
      "Room/Unit Type": "Classic",
      "Room/Unit Name": "Room 8",
      Currency: "GBP",
      "Total Revenue": "260.00",
      "Paid Amount": "260.00",
      "Room/Unit Revenue": "245.00",
      "Other Revenue": "15.00",
      "Booking Status": "Checked in",
      Channel: "OTA",
    }),
  },
  {
    internalCompany: "Crown H&H",
    source: recordFrom(BOOKING_HEADERS, {
      Property: "Crown House",
      "Booking Date": "2026-09-28",
      "Booking Reference": "EV-28488",
      "Order Reference": "ORD-28488",
      "Guest First Name": "Noah",
      "Guest Last Name": "Thompson",
      "Check In": "2026-10-09",
      "Check Out": "2026-10-12",
      Nights: "3",
      "Room/Unit Type": "Deluxe",
      "Room/Unit Name": "Room 3",
      Currency: "GBP",
      "Total Revenue": "180.00",
      "Paid Amount": "80.00",
      "Room/Unit Revenue": "180.00",
      "Other Revenue": "100.00",
      "Booking Status": "Awaiting payment",
      Channel: "OTA",
    }),
  },
];

export const paymentSources: PaymentSource[] = [
  {
    source: recordFrom(PAYMENT_HEADERS, {
      ReceivedDateTime: "2026-10-01 09:10",
      PaymentID: "PY-63018",
      Forename: "Amelia",
      Company: "Crown House",
      OrderReference: "ORD-28491",
      BookingReference: "EV-28491",
      PaymentMethod: "Cash",
      Description: "Arrival payment",
      Cash1: "50.00",
      Direct1: "50.00",
    }),
  },
  {
    source: recordFrom(PAYMENT_HEADERS, {
      ReceivedDateTime: "2026-10-01 09:11",
      PaymentID: "PY-63017",
      Forename: "Amelia",
      Company: "Crown House",
      OrderReference: "ORD-28491",
      BookingReference: "EV-28491",
      PaymentMethod: "Card",
      Description: "Arrival payment",
      Card1: "50.00",
      Direct1: "50.00",
    }),
  },
  {
    source: recordFrom(PAYMENT_HEADERS, {
      ReceivedDateTime: "2026-09-30 10:00",
      PaymentID: "PY-63016",
      Forename: "Oliver",
      Company: "Crown Harbor",
      OrderReference: "ORD-28490",
      BookingReference: "EV-28490",
      PaymentMethod: "Card",
      Description: "Room balance",
      Card1: "67.00",
      Direct1: "67.00",
    }),
  },
  {
    source: recordFrom(PAYMENT_HEADERS, {
      ReceivedDateTime: "2026-09-29 12:20",
      PaymentID: "PY-63015",
      Forename: "Sofia",
      Company: "Crown Orlando",
      OrderReference: "ORD-28489",
      BookingReference: "EV-28489",
      PaymentMethod: "Bank Transfer",
      Description: "Deposit",
      Direct1: "100.00",
    }),
  },
  {
    source: recordFrom(PAYMENT_HEADERS, {
      ReceivedDateTime: "2026-09-29 14:30",
      PaymentID: "PY-63014",
      Forename: "Sofia",
      Company: "Crown Orlando",
      OrderReference: "ORD-28489",
      BookingReference: "EV-28489",
      PaymentMethod: "PayPal",
      Description: "Room balance",
      Direct1: "160.00",
    }),
  },
  {
    source: recordFrom(PAYMENT_HEADERS, {
      ReceivedDateTime: "2026-09-28 15:00",
      PaymentID: "PY-63013",
      Forename: "Noah",
      Company: "Crown House",
      OrderReference: "ORD-28488",
      BookingReference: "EV-28488",
      PaymentMethod: "External Card",
      Description: "OTA collection",
      Direct1: "80.00",
    }),
  },
];

export const bookingReportRows = buildBookingReportRows(bookingSources, paymentSources);
export const paymentReportRows = buildPaymentReportRows(paymentSources);
